# Golang CircleCI 2.0 configuration file
# See https://circleci.com/docs/2.0/language-go/
version: 2.1
orbs:
  docker: circleci/docker@1.0.1
jobs:
  build:
    working_directory: /home/circleci/aquila
    docker:
      - image: circleci/golang:1.15
    environment:
      DEBIAN_FRONTEND: noninteractive
    steps:
      - checkout
      - run: go version
      - run: go env
      - run: go get -v .

      - run: ./build_all.sh
      - store_artifacts:
          path: ./bin/
          destination: /artifacts/
      - run: ./make_release.sh

      - setup_remote_docker:
          version: 18.09.3
      - run: docker version
      - docker/check
      - docker/build:
          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
          tag: latest,v$CIRCLE_BUILD_NUM
          extra_build_args: "--build-arg=BUILD_NUM=$CIRCLE_BUILD_NUM"
      - docker/push:
          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
          tag: latest,v$CIRCLE_BUILD_NUM
