# Golang CircleCI 2.0 configuration file
# See https://circleci.com/docs/2.0/language-go/
version: 2.1
orbs:
  docker: circleci/docker@1.0.1
jobs:
  build:
    working_directory: /home/circleci/aquila
    docker:
      - image: golang:1.16
    environment:
      DEBIAN_FRONTEND: noninteractive
    steps:
      - run: apt update
      - run: apt -y upgrade
      - checkout

      - run: go version
      - run: go env
      - run: go get -v .
      - run: go test -v .

      - run: ./build_all.sh
      - store_artifacts:
          path: ./bin/
          destination: /artifacts/
