# Golang CircleCI 2.0 configuration file
# See https://circleci.com/docs/2.0/language-go/
version: 2.1
orbs:
  docker: circleci/docker@1.4.0
jobs:
  build:
    working_directory: /home/circleci/aquila
    docker:
      - image: golang
    environment:
      DEBIAN_FRONTEND: noninteractive
    steps:
      - run: apt update
      - run: apt -y upgrade
      - checkout

      - run: go version
      - run: go env
      - run: go get -v .
      - run: ./build_all.sh
      - store_artifacts:
          path: ./bin/
          destination: /artifacts/

      - run: apt -y install wget tar xz-utils jq
      - run: ./download_zig.sh 0.9.0-dev.689+507dc1f2e
      - run: zig version
      - run: zig env

      - run: zigmod ci
      - run: ./build_all_zig.sh
      - store_artifacts:
          path: ./zig-out/bin/
          destination: /artifacts/

      - run: ./make_release.sh

      - setup_remote_docker:
          version: 18.09.3
      - docker/check
      - docker/build:
          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
          tag: latest,v$CIRCLE_BUILD_NUM
          extra_build_args: "--build-arg=BUILD_NUM=$CIRCLE_BUILD_NUM"
      - docker/push:
          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
          tag: latest,v$CIRCLE_BUILD_NUM
