name: CI

on:
  push:
    branches: [master]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      # debug info about this machine
      - run: uname -a
      - run: free
      - run: env
      - run: mount
      - run: lscpu
      - run: lsmem
      - run: lsblk
      - run: lspci
      - run: lsipc
      - run: whoami

      # Get the code
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: git fetch --all --tags
      - run: top -b -n 1 | head -n5

      # Zig
      - uses: goto-bus-stop/setup-zig@v1
        with:
          version: "0.10.0-dev.1018+0bdc3d8f4"
      - run: zig version
      - run: zig env
      - uses: nektro/actions-setup-zigmod@v1
      - run: zigmod version
      - run: zigmod ci
      - run: cat ./deps.zig
      - run: zig build
      - run: ./build_release.sh x86_64-linux-musl
      - run: ./build_release.sh aarch64-linux-musl
      - run: ./build_release.sh riscv64-linux-musl
      - run: ./build_release.sh powerpc64-linux-musl

      # Github Release
      - run: ./changelog.sh
      - run: zigmod aq install 1/nektro/ghr
      - run: ./make_release.sh ${{ secrets.GITHUB_TOKEN }}

      # Docker image
      - run: echo "RELEASE_NUM=$(./release_num.sh)" >> $GITHUB_ENV
      - run: echo ${{ env.RELEASE_NUM }}
      - uses: docker/build-push-action@v1
        with:
          username: nektro
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
          repository: ${{ env.GITHUB_REPOSITORY }}
          tags: latest,r${{ env.RELEASE_NUM }}
