name: Zig CI

on:
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v1
        with:
          version: "0.10.0-dev.531+3eb8d01f5"

      - run: zig version
      - run: zig env
      - uses: nektro/actions-setup-zigmod@v1
      - run: zigmod version
      - run: zigmod ci
      - run: zig build
